
services:
  - type: web
    name: emotion-detection
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_py.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
